spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fittogether
    username: root
    password: 123$qweR
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.paranhos@gmail.com
    password: kdzi wbmv gkjj ouja
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com