security:
  jwt:
    public-key: classpath:app.pub
    private-key: classpath:app.key
spring:
  config:
    import: classpath:app.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fittogether
    username: root
    password: 123$qweR
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/fittogether
    user: root
    password: 123$qweR
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.paranhos@gmail.com
    password: kdzi wbmv gkjj ouja
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com