CREATE TABLE IF NOT EXISTS level (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    min INT NOT NULL UNIQUE,
    max int NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);