CREATE TABLE validation_codes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    validated BOOLEAN NOT NULL,
    code INT NOT NULL,
    duration INT NOT NULL DEFAULT 90,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);